/* Programme content: exercises, stages, safety rules.
   To use a specific YouTube video for an exercise, add  video: 'https://youtu.be/XXXX'  to it.
   Without it the app opens a YouTube search for that exercise. */
(function () {
  const KA = (window.KA = window.KA || {});

  const EX = {
    /* ---------- warm-up ---------- */
    march: {
      name: 'Gentle march on the spot', fig: 'march', muscles: 'Whole leg, heart and lungs',
      setup: 'Stand tall next to a wall or counter. Fingertips on it for balance.',
      verbs: { hold: 'March' },
      steps: ['Stand tall, fingertips on a wall or counter.', 'Lift one knee a little, then the other, like a slow walk on the spot.', 'Keep it easy: you should be able to chat.'],
      cues: ['Lift the knee only to a comfortable height.', 'Swing your arms gently.'],
      mistakes: ['Going fast, which makes the knee work harder than you want yet.'],
      easier: 'Sit on a chair and march seated.', harder: 'Lift the knees a little higher.',
      yt: 'gentle marching on the spot warm up knee physiotherapy',
    },
    ankle: {
      name: 'Ankle pumps', fig: 'ankle', muscles: 'Calf and shin, blood flow',
      setup: 'Lie on your back with both legs straight.',
      verbs: { up: 'Point toes', down: 'Pull toes up' },
      steps: ['Lie on your back, legs straight.', 'Point your toes away from you.', 'Pull them back toward your face.'],
      cues: ['Smooth and steady, not a flick.'], mistakes: ['Rushing: use the whole range.'],
      easier: 'Do it sitting.', harder: 'Draw the alphabet with your toes.',
      yt: 'ankle pumps exercise physiotherapy how to',
    },
    heelslide: {
      name: 'Heel slides', fig: 'heelslide', muscles: 'Knee mobility, thigh and hamstring', uni: true,
      setup: 'Lie on your back, legs straight. A sock on a smooth floor helps your heel slide.',
      verbs: { up: 'Slide heel in', hold: 'Pause', down: 'Slide out' },
      steps: ['Lie on your back, legs straight.', 'Slowly slide one heel toward your bottom, bending the knee.', 'Stop at the first point of tightness or discomfort. Never force it.', 'Slide the heel back out until the leg is straight.'],
      cues: ['Keep your kneecap pointing at the ceiling.', 'Heel stays on the floor.'],
      mistakes: ['Pushing into a sharp pinch.', 'Letting the knee fall sideways.'],
      easier: 'Use a towel under the heel to slide it.', harder: 'Hold the bent position for 5 seconds.',
      yt: 'heel slides knee range of motion exercise physiotherapy',
    },

    /* ---------- main ---------- */
    quadset: {
      name: 'Quad set (towel roll)', fig: 'quadset', muscles: 'Front of thigh (quadriceps)', uni: true,
      setup: 'Lie on your back. Roll a towel and place it under the knee you are working. Other knee bent, foot flat.',
      verbs: { up: 'Press down', hold: 'Hold', down: 'Relax' },
      why: 'Teaches the thigh muscle to switch on, and to fully straighten the knee, without loading the joint.',
      steps: ['Lie on your back with a rolled towel under the knee. Other knee bent, foot flat.', 'Tighten the thigh muscle and press the back of the knee down into the towel.', 'Your heel may lift slightly and toes pull toward you.', 'Hold, then relax completely before the next one.'],
      cues: ['You should see and feel the thigh muscle bunch up.', 'Breathe normally, do not hold your breath.'],
      mistakes: ['Squeezing the buttocks instead of the thigh.', 'Not relaxing fully between reps.'],
      easier: 'Hold for 3 seconds, or squeeze at half effort.', harder: 'Remove the towel and press the whole leg flat.',
      yt: 'quad set exercise knee physiotherapy how to',
    },
    slr: {
      name: 'Straight leg raise', fig: 'slr', muscles: 'Front of thigh and hip flexors', uni: true,
      setup: 'Lie on your back. Bend the other knee with the foot flat.',
      verbs: { up: 'Lift', hold: 'Hold', down: 'Lower' },
      why: 'Builds thigh strength with the knee held straight, so there is very little load through the joint.',
      steps: ['Lie on your back. Bend the knee you are not working, foot flat.', 'Tighten the thigh of the straight leg first (a quad set).', 'Keeping the knee locked straight, lift the leg until it is level with the other knee.', 'Hold, then lower slowly.'],
      cues: ['Toes pulled toward you.', 'Low back stays flat on the floor.'],
      mistakes: ['Knee bending as the leg lifts.', 'Lifting too high and arching the back.', 'Dropping the leg quickly.'],
      easier: 'Lift only a hand-width off the floor.', harder: 'Add a 0.5 kg ankle weight (week 5 onward, only if easy).',
      yt: 'straight leg raise exercise knee physiotherapy how to',
    },
    bridge: {
      name: 'Glute bridge', fig: 'bridge', muscles: 'Buttocks and back of thigh',
      setup: 'Lie on your back, knees bent, feet flat and hip-width apart.',
      verbs: { up: 'Lift hips', hold: 'Hold', down: 'Lower' },
      why: 'Strong buttock muscles take load off the knee when you walk, climb stairs and stand up.',
      steps: ['Lie on your back, knees bent, feet flat, arms by your sides.', 'Squeeze your buttocks and lift your hips until shoulders, hips and knees make a line.', 'Hold, then lower one bone of the spine at a time.'],
      cues: ['Push through the whole foot.', 'Ribs down, do not arch the back.'],
      mistakes: ['Pushing up with the back instead of the buttocks.', 'Feet too close to the bottom, which strains the hamstrings.'],
      easier: 'Smaller lift, shorter hold.', harder: 'Single-leg bridge (stage 4).',
      yt: 'glute bridge exercise knee rehab how to physiotherapy',
    },
    bridge1: {
      name: 'Single-leg bridge', fig: 'bridge1', muscles: 'Buttocks and back of thigh', uni: true,
      setup: 'Lie on your back, knees bent, feet flat.',
      verbs: { up: 'Lift hips', hold: 'Hold', down: 'Lower' },
      steps: ['Start as for a normal bridge.', 'Straighten one leg so it points up in line with your body.', 'Squeeze the buttock of the foot that is on the floor and lift your hips.', 'Hold, then lower with control.'],
      cues: ['Keep the hips level, do not let one side drop.'],
      mistakes: ['Twisting through the hips.', 'Rushing the lowering.'],
      easier: 'Go back to a two-leg bridge.', harder: 'Longer hold, or rest the lifted foot on a chair.',
      yt: 'single leg glute bridge exercise how to physiotherapy',
    },
    clamshell: {
      name: 'Clamshell', fig: 'clamshell', muscles: 'Side of the buttock (gluteus medius)', uni: true,
      sideLabels: ['Left side up', 'Right side up'],
      setup: 'Lie on your side, hips stacked, knees bent about 45 degrees (not tucked right up). Head on a pillow.',
      verbs: { up: 'Open knee', hold: 'Hold', down: 'Close' },
      why: 'Wakes up the side-of-hip muscles that keep your knee tracking straight.',
      steps: ['Lie on your side, hips and shoulders stacked, knees bent about 45 degrees, feet together.', 'Keeping your feet touching, lift the top knee toward the ceiling.', 'Do not let your pelvis roll back.', 'Hold, then lower slowly.'],
      cues: ['A hand on your hip can check it is not rolling back.', 'Feel it at the side of the buttock, not the front of the thigh.'],
      mistakes: ['Rolling the whole body backwards.', 'Lifting too high.'],
      easier: 'Smaller range, no hold.', harder: 'Add a light band above the knees (week 5).',
      yt: 'clamshell exercise glute medius how to physiotherapy',
    },
    hipabd: {
      name: 'Standing hip lift to the side', fig: 'hipabd', muscles: 'Side of the buttock (gluteus medius)', uni: true,
      sideLabels: ['Left leg lifts', 'Right leg lifts'],
      setup: 'Stand side-on to a wall, one hand on it. Stand tall on the leg nearest the wall.',
      verbs: { up: 'Lift out', hold: 'Hold', down: 'Lower' },
      steps: ['Stand tall, hand on the wall.', 'Keeping the toes pointing forward and the knee straight, lift the outer leg out to the side.', 'Do not lean the body away.', 'Hold, then lower with control.'],
      cues: ['Stay tall like a book is balanced on your head.', 'Small movement, about 30 degrees.'],
      mistakes: ['Leaning the trunk sideways.', 'Swinging the leg.'],
      easier: 'Use both hands on the wall.', harder: 'Add a light loop band above the knees.',
      yt: 'standing hip abduction exercise how to physiotherapy',
    },
    calfraise: {
      name: 'Calf raise', fig: 'calfraise', muscles: 'Calf',
      setup: 'Stand facing a wall or counter, fingertips resting on it.',
      verbs: { up: 'Rise up', hold: 'Hold', down: 'Lower' },
      steps: ['Stand tall, feet hip-width apart, fingertips on a wall.', 'Rise slowly onto the balls of your feet.', 'Hold at the top, then lower slowly.'],
      cues: ['Rise straight up, do not roll outward.', 'Knees stay soft but straight.'],
      mistakes: ['Bouncing.', 'Leaning heavily on the wall.'],
      easier: 'Hold the wall with both hands.', harder: 'Single-leg calf raise (stage 4).',
      yt: 'calf raise exercise how to physiotherapy',
    },
    hamcurl: {
      name: 'Standing hamstring curl', fig: 'hamcurl', muscles: 'Back of thigh (hamstrings)', uni: true,
      sideLabels: ['Left leg curls', 'Right leg curls'],
      setup: 'Stand tall, hand on a wall or counter. Weight on the leg that is not curling.',
      verbs: { up: 'Curl heel up', hold: 'Hold', down: 'Lower' },
      steps: ['Stand tall, one hand on a wall.', 'Bend one knee and bring the heel up behind you, to about a right angle only.', 'Keep your thighs side by side.', 'Hold, then lower slowly.'],
      cues: ['Do not swing the thigh forward or back.'],
      mistakes: ['Going past a right angle. This programme avoids deep bends.', 'Arching the back.'],
      easier: 'Smaller bend.', harder: 'Add a light ankle weight.',
      yt: 'standing hamstring curl exercise how to physiotherapy',
    },
    sitstand: {
      name: 'Sit to stand (chair)', fig: 'sitstand', muscles: 'Thighs and buttocks',
      setup: 'Sturdy chair against a wall, feet hip-width apart and slightly behind your knees.',
      verbs: { up: 'Stand up', hold: 'Stand tall', down: 'Sit slowly' },
      why: 'The most useful everyday movement: it is the same muscle pattern as getting off the sofa or toilet.',
      steps: ['Sit near the front edge of a sturdy chair, feet hip-width apart.', 'Lean forward slightly so your nose is over your toes.', 'Stand up by pushing through your whole foot.', 'Stand tall, then sit down slowly, taking about 3 seconds.'],
      cues: ['Knees track over the second toe, not collapsing inward.', 'Take the weight evenly through both feet.'],
      mistakes: ['Dropping into the chair.', 'Using momentum.', 'Feet too far forward.'],
      easier: 'Use a higher seat (add a firm cushion) and push off with your hands.', harder: 'Arms crossed, lower seat, or a longer lowering phase.',
      yt: 'sit to stand exercise knee physiotherapy how to',
    },
    balance: {
      name: 'Single-leg balance', fig: 'balance', muscles: 'Hips, ankle and thigh stabilisers', uni: true,
      sideLabels: ['Stand on the left leg', 'Stand on the right leg'],
      setup: 'Stand next to a wall or counter within easy reach.',
      verbs: { hold: 'Balance' },
      steps: ['Stand tall near a wall.', 'Shift your weight to one leg and lift the other foot a few centimetres.', 'Keep the standing knee soft, not locked.', 'Hold for the time shown, then swap legs.'],
      cues: ['Eyes on a fixed point ahead.', 'Touch the wall with one finger only if you need to.'],
      mistakes: ['Locking the knee back.', 'Hitching the hip up.'],
      easier: 'Keep a toe touching the floor.', harder: 'Close your eyes, or turn your head slowly side to side.',
      yt: 'single leg balance exercise knee rehab physiotherapy',
    },
    tke: {
      name: 'Band knee straightening', fig: 'tke', muscles: 'Front of thigh (quadriceps)', uni: true,
      sideLabels: ['Left knee', 'Right knee'],
      equipment: ['band'],
      setup: 'Loop a resistance band around a sturdy post at knee height, then step into the loop so it sits behind your knee. Step back to tension it.',
      verbs: { up: 'Straighten', hold: 'Squeeze', down: 'Soften' },
      why: 'Trains the last few degrees of straightening, which is needed for a normal walking pattern.',
      steps: ['Anchor the band at knee height. Put the loop just behind the knee you are working.', 'Start with that knee slightly bent.', 'Straighten the knee fully, squeezing the thigh.', 'Hold, then let the knee soften slowly.'],
      cues: ['Do not lock the knee back hard.', 'Stand tall.'],
      mistakes: ['Leaning back to straighten.', 'A band so strong the knee is yanked back.'],
      easier: 'Lighter band or no band.', harder: 'Stronger band or a longer hold.',
      yt: 'terminal knee extension band exercise how to physiotherapy',
    },
    stepup: {
      name: 'Step-up (low step)', fig: 'stepup', muscles: 'Thigh and buttocks', uni: true,
      sideLabels: ['Left leg steps up', 'Right leg steps up'],
      equipment: ['step'],
      setup: 'Use a sturdy low step (bottom stair or step, about 10 to 15 cm). Hold a rail or wall.',
      verbs: { up: 'Step up', hold: 'Stand tall', down: 'Lower slowly' },
      why: 'Direct practice for stairs and curbs.',
      steps: ['Stand facing the step, hand on a rail.', 'Place your whole foot on the step.', 'Press through that heel and stand tall on the step.', 'Lower the other foot back down slowly, taking about 3 seconds.'],
      cues: ['Knee in line with the second toe.', 'Push with the stepping leg, not the back foot.'],
      mistakes: ['Pushing off with the back leg.', 'Dropping down fast.', 'Too high a step too soon.'],
      easier: 'Lower step, or hold with both hands.', harder: 'Higher step (15 to 20 cm) and no hand support.',
      yt: 'step up exercise knee rehab how to physiotherapy',
    },
    bandwalk: {
      name: 'Side-step with band', fig: 'bandwalk', muscles: 'Side of the buttock', uni: true,
      sideLabels: ['Step to the left', 'Step to the right'],
      equipment: ['band'],
      setup: 'Loop band just above your knees. Feet hip-width apart, knees soft. Space to step sideways.',
      verbs: { up: 'Step out', hold: 'Pause', down: 'Step in' },
      steps: ['Band just above the knees, feet hip-width apart.', 'Take a small step sideways, keeping the toes forward and the band tight.', 'Bring the other foot in so the feet are hip-width again.', 'Keep the tension all the way.'],
      cues: ['Slight bend in the knees, as if about to sit.', 'Small steps, stay tall.'],
      mistakes: ['Feet coming together (band goes slack).', 'Toes turning out.'],
      easier: 'Light band, or do it with no band.', harder: 'Stronger band, or slow the steps.',
      yt: 'banded lateral walk side step exercise how to physiotherapy',
    },

    /* ---------- cool-down ---------- */
    hamstretch: {
      name: 'Hamstring stretch (lying, towel)', fig: 'hamstretch', muscles: 'Back of thigh', uni: true,
      sideLabels: ['Left leg up', 'Right leg up'],
      setup: 'Lie on your back. Loop a towel around the ball of one foot.',
      verbs: { hold: 'Stretch' },
      steps: ['Lie on your back, other knee bent with foot flat.', 'Loop a towel round the ball of the foot and raise the leg.', 'Gently draw the leg toward you until you feel a stretch behind the thigh.', 'Hold. A slight bend in the knee is fine.'],
      cues: ['Stretch, not pain.', 'Breathe out slowly.'],
      mistakes: ['Pulling hard.', 'Lifting the head and tensing the neck.'],
      easier: 'Leg lower, or knee more bent.', harder: 'Straighten the knee a little more.',
      yt: 'lying hamstring stretch with towel how to physiotherapy',
    },
    calfstretch: {
      name: 'Calf stretch (wall)', fig: 'calfstretch', muscles: 'Calf', uni: true,
      sideLabels: ['Left leg back', 'Right leg back'],
      setup: 'Stand facing a wall, hands on it at shoulder height.',
      verbs: { hold: 'Stretch' },
      steps: ['Stand facing the wall, step one foot back.', 'Keep the back leg straight and the heel on the floor.', 'Bend the front knee slightly and lean toward the wall.', 'Hold when you feel the stretch in the back calf.'],
      cues: ['Toes point straight forward.', 'Heel stays down.'],
      mistakes: ['Back heel lifting.', 'Bouncing.'],
      easier: 'Shorter step back.', harder: 'Step back a little further.',
      yt: 'standing calf stretch against wall how to physiotherapy',
    },
    hipfront: {
      name: 'Hip-front stretch (standing)', fig: 'hipfront', muscles: 'Front of hip', uni: true,
      sideLabels: ['Left leg back', 'Right leg back'],
      setup: 'Stand in a short stride, hand on a wall for balance. No kneeling.',
      verbs: { hold: 'Stretch' },
      steps: ['Stand in a short stride, holding a wall.', 'Keep the back leg straight, front knee only slightly bent.', 'Tuck your tailbone under and ease the hips gently forward.', 'Feel the stretch at the front of the back hip.'],
      cues: ['Stay tall, do not arch the back.', 'Do not push the front knee past the toes.'],
      mistakes: ['Arching the lower back.', 'Bending the front knee deeply.'],
      easier: 'Shorter stride.', harder: 'Raise the arm on the back-leg side overhead.',
      yt: 'standing hip flexor stretch without kneeling physiotherapy',
    },
  };
  Object.keys(EX).forEach((id) => { EX[id].id = id; EX[id].verbs = Object.assign({ up: 'Up', hold: 'Hold', down: 'Down' }, EX[id].verbs); });

  const WARM = [
    { id: 'march', sets: 1, reps: 1, hold: 60 },
    { id: 'ankle', sets: 1, reps: 10, up: 1, down: 1 },
    { id: 'heelslide', sets: 1, reps: 5, up: 2, hold: 1, down: 2, rest: 5 },
  ];
  const cool = (h) => [
    { id: 'hamstretch', sets: 1, reps: 1, hold: h },
    { id: 'calfstretch', sets: 1, reps: 1, hold: h },
    { id: 'hipfront', sets: 1, reps: 1, hold: h },
  ];

  const STAGES = [
    {
      n: 1, name: 'Wake up the muscles', weeks: '1 to 2', weekCount: 2,
      goal: 'Learn to switch on the right muscles before loading them. Light effort, plenty of control.',
      rules: ['2 sets of each exercise.', '5-second holds.', 'About 20 minutes (shorter if you train only the sore knee).', 'Effort about 4 out of 10.'],
      equipment: ['towel', 'wall'], walk: 'Easy walk on flat ground, 10 minutes, on non-session days.',
      warm: WARM, cool: cool(20),
      main: [
        { id: 'quadset', sets: 2, reps: 5, up: 1, hold: 5, down: 2, rest: 15 },
        { id: 'slr', sets: 2, reps: 4, up: 2, hold: 5, down: 2, rest: 15 },
        { id: 'bridge', sets: 2, reps: 5, up: 2, hold: 5, down: 2, rest: 20 },
        { id: 'clamshell', sets: 2, reps: 5, up: 1, hold: 3, down: 2, rest: 15 },
        { id: 'calfraise', sets: 2, reps: 6, up: 2, hold: 2, down: 2, rest: 15 },
      ],
    },
    {
      n: 2, name: 'Build control', weeks: '3 to 4', weekCount: 2,
      goal: 'More repetitions, a third set on the main lifts, and standing exercises that copy daily life.',
      rules: ['2 to 3 sets.', 'Slow lowering, 3 seconds.', 'About 25 minutes.', 'Effort about 5 out of 10.'],
      equipment: ['towel', 'chair', 'wall'], walk: 'Walk 15 minutes at a comfortable pace on non-session days.',
      warm: WARM, cool: cool(30),
      main: [
        { id: 'slr', sets: 2, reps: 6, up: 2, hold: 3, down: 2, rest: 15 },
        { id: 'bridge', sets: 2, reps: 8, up: 2, hold: 4, down: 2, rest: 20 },
        { id: 'hipabd', sets: 2, reps: 6, up: 2, hold: 2, down: 2, rest: 15 },
        { id: 'sitstand', sets: 2, reps: 8, up: 2, hold: 1, down: 3, rest: 30, note: 'High seat, hands may help.' },
        { id: 'hamcurl', sets: 2, reps: 6, up: 2, hold: 1, down: 2, rest: 15 },
        { id: 'balance', sets: 2, reps: 1, hold: 20, rest: 15, note: 'Fingertips on the wall.' },
      ],
    },
    {
      n: 3, name: 'Add load', weeks: '5 to 7', weekCount: 3,
      goal: 'Bands and a low step join in. Same slow control, more resistance.',
      rules: ['3 sets.', '3-second lowering.', 'About 30 minutes.', 'Effort about 6 out of 10.'],
      equipment: ['band', 'step', 'chair', 'wall', 'towel'], walk: 'Walk 20 minutes, or use a stationary bike with the seat high and low resistance.',
      warm: WARM, cool: cool(30),
      main: [
        { id: 'tke', sets: 2, reps: 8, up: 2, hold: 3, down: 2, rest: 20 },
        { id: 'stepup', sets: 2, reps: 6, up: 2, hold: 1, down: 3, rest: 25, note: 'Low step, one hand on a rail.' },
        { id: 'sitstand', sets: 3, reps: 8, up: 2, hold: 1, down: 3, rest: 30, note: 'Normal chair, no hands.' },
        { id: 'bandwalk', sets: 2, reps: 8, up: 2, hold: 0, down: 1, rest: 20 },
        { id: 'bridge', sets: 2, reps: 8, up: 2, hold: 4, down: 2, rest: 20 },
        { id: 'balance', sets: 2, reps: 1, hold: 25, rest: 15 },
      ],
    },
    {
      n: 4, name: 'Strong and steady', weeks: '8 to 10', weekCount: 3,
      goal: 'Single-leg strength and balance so the knee copes with everyday life and walking further.',
      rules: ['3 sets.', 'Slow, controlled reps.', 'About 30 to 35 minutes.', 'Effort about 6 to 7 out of 10, never knee pain.'],
      equipment: ['band', 'step', 'chair', 'wall', 'towel'], walk: 'Walk 25 to 30 minutes, including gentle slopes if they feel fine.',
      warm: WARM, cool: cool(30),
      main: [
        { id: 'stepup', sets: 3, reps: 6, up: 2, hold: 1, down: 3, rest: 30, note: 'Slightly higher step, no hands if steady.' },
        { id: 'bridge1', sets: 2, reps: 6, up: 2, hold: 3, down: 2, rest: 20 },
        { id: 'sitstand', sets: 3, reps: 8, up: 2, hold: 1, down: 3, rest: 30, note: 'Arms crossed, tap the seat lightly.' },
        { id: 'bandwalk', sets: 2, reps: 8, up: 2, hold: 0, down: 1, rest: 20, note: 'Slightly stronger band.' },
        { id: 'tke', sets: 2, reps: 8, up: 2, hold: 4, down: 2, rest: 20 },
        { id: 'calfraise', sets: 2, reps: 6, up: 2, hold: 1, down: 2, rest: 15, uni: true, note: 'One leg at a time, fingertips on the wall.' },
        { id: 'balance', sets: 2, reps: 1, hold: 30, rest: 15, note: 'Try turning your head slowly side to side.' },
      ],
    },
  ];

  const EQUIP = {
    towel: { name: 'Towel', hint: 'A bath towel for the towel roll and stretch.' },
    wall: { name: 'Wall or kitchen counter', hint: 'Something steady to rest fingertips on.' },
    chair: { name: 'Sturdy chair', hint: 'No wheels, against a wall, seat about 45 cm high.' },
    band: { name: 'Resistance band(s)', hint: 'A light to medium loop band. A thicker one later if needed.' },
    step: { name: 'Low step', hint: 'Bottom stair or a sturdy step, 10 to 15 cm, with a rail nearby.' },
  };

  KA.Data = { EX, STAGES, EQUIP };
})();
